# slurm uid/gid match cyclecloud-slurm cookbook values
slurm_uid: 11100
slurm_gid: 11100
slurm_version: 22.05.5-1
cyclecloud_slurm_release: 2.6.2
pyxis_version: 0.12.0
build_rpms: true
accounting_enabled: false
cc_admin: hpcadmin
cc_password: 
